/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.0.13" // Ajout du plugin JavaFX
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {

    implementation("org.openjfx:javafx-controls:21.0.2")
    implementation("org.openjfx:javafx-fxml:21.0.2")
    implementation("org.openjfx:javafx-graphics:21.0.2")

    implementation("org.mariadb.jdbc:mariadb-java-client:3.5.2")

    implementation("org.mindrot:jbcrypt:0.4")
    
    // Dépendance JPA

    // Framework de test

    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
}

javafx{
    version = "21.0.2" // Version JavaFX
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.graphics") // Modules à inclure
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "cc.lery.AppScene"
}

tasks.register<Copy>("copyJavaFXModules") {
    from({
        configurations.runtimeClasspath.get().filter { it.name.startsWith("javafx") }
    })
    into(layout.buildDirectory.dir("javafx"))
}
tasks.named("build") {
    dependsOn("copyJavaFXModules")
}
